#!/bin/bash -x

. ./hooks/env

for i in ${ARCH_LIST}; do
  PLATFORMS="${PLATFORMS}linux/${i},"
done

${DOCKER_CLI} run --rm --privileged multiarch/qemu-user-static --reset -p yes
${DOCKER_CLI} -v
${DOCKER_CLI} buildx install
${DOCKER_CLI} buildx create --name mybuilder
${DOCKER_CLI} buildx use mybuilder
${DOCKER_CLI} buildx inspect --boostrap
${DOCKER_CLI} build \
  --build-arg VERSION="${PKG_VER}"  \
  --build-arg COMMIT="${SOURCE_COMMIT}" \
  --build-arg BRANCH="${SOURCE_BRANCH}" \
  --build-arg VCS_URL="${VCS_URL}" \
  --build-arg BUILD_DATE="${BUILD_DATE}" \
  --build-arg ALPINE_VER="${ALPINE_VER}" \
  --build-arg PYTHON_VER="${PYTHON_VER}" \
  --build-arg DOCKER_ARCH="${DOCKER_ARCH}" \
  --build-arg BASEIMAGE_ARCH="${BASEIMAGE_ARCH}" \
  --build-arg PKG_ARCH="${PKG_ARCH}" \
  --build-arg QEMU_ARCH="${QEMU_ARCH}" \
-f "${DOCKERFILE_PATH}" \
-t "${DOCKER_REPO}:latest" \
-t "${IMAGE_NAME}" \
--platform ${PLATFORMS%%,} \
--push . \
| while read line ; do echo "$(date)| $line"; done;
